/* Copyright © 2026 BestProject Team */
#ifndef GAME_CLIENT_COMPONENTS_BESTCLIENT_VERSION_H
#define GAME_CLIENT_COMPONENTS_BESTCLIENT_VERSION_H

#define BESTCLIENT_BUILD_DATE "28.05 00:00"
#define BESTCLIENT_VERSIONNR 100
#define BESTCLIENT_VERSION "2.3 stable-beta"

#endif
