name: Fast Build

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    env:
      CARGO_HTTP_MULTIPLEXING: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macOS-latest, windows-latest]
        include:
        - os: ubuntu-22.04
          cmake-args: -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISCORD=ON -DDISCORD_DYNAMIC=ON -DWEBSOCKETS=OFF -DPREFER_BUNDLED_LIBS=ON -DAUTOUPDATE=ON
          cmake-init-env: CXXFLAGS= 
          package-file: "*-linux_x86_64.tar.xz"
        - os: macOS-latest
          cmake-args: -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISCORD=ON -DWEBSOCKETS=OFF -DPREFER_BUNDLED_LIBS=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib -DCMAKE_FIND_FRAMEWORK=LAST
          cmake-init-env: CXXFLAGS= 
          package-file: "*-macos.dmg"
        - os: windows-latest
          cmake-args: -A x64 -DDISCORD=ON -DTOOLS=OFF -DAUTOUPDATE=ON -DVULKAN=ON
          cmake-init-env: CXXFLAGS= LDFLAGS=
          package-file: "*-win64.zip"
        # - os: windows-latest
        #   cmake-args: -A Win32 -DDISCORD=ON
        #   cmake-init-env: CXXFLAGS= LDFLAGS=
        #   package-file: "*-win32.zip"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        # mount: /var/lib/grub/esp: special device /dev/disk/by-id/scsi-... does not exist.
        # sudo apt-get upgrade -y
        sudo apt-get install pkg-config cmake ninja-build libcurl4-openssl-dev libdbus-1-dev libfreetype6-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libsdl2-dev libsqlite3-dev libvulkan-dev glslang-tools spirv-tools libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libx264-dev libpng-dev valgrind gcovr libglew-dev -y

    - name: Prepare macOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update || true
        brew install ffmpeg molten-vk ninja pkg-config || true
        brew upgrade freetype
        pip3 install --break-system-packages dmgbuild
        echo /Library/Frameworks/Python.framework/Versions/3.12/bin >> $GITHUB_PATH
        sudo rm -rf /Library/Developer/CommandLineTools

    - name: Add rust macOS
      if: contains(matrix.os, 'macOS')
      run: |
        rustup default stable
        rustup update
        rustup target add x86_64-apple-darwin aarch64-apple-darwin

    - name: Add rust for Windows 32
      if: contains(matrix.cmake-args, '-A Win32')
      run: |
        rustup default stable
        rustup target add i686-pc-windows-msvc

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
          workspaces: |
              src/mastersrv
              src/masterping
              ./

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.3.296.0
        cache: true

    - name: Build in release mode
      env:
        VERSION: ${{ secrets.VERSION }}
      shell: bash
      run: |
        VERSION_FILE="$GITHUB_WORKSPACE/versioninfo.h"
        printf '%s' "$VERSION" | base64 -d > "$VERSION_FILE"
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            export MSYS_ARG_CONV_EXCL="/FI"
            POST_FLAGS="-DCMAKE_CXX_FLAGS=\"/FI$VERSION_FILE\""
            ENVFLAGS=""
        else
            ENVFLAGS="CXXFLAGS=-include$VERSION_FILE"
            POST_FLAGS=""
        fi

        if [[ "${{ matrix.os }}" == "macOS-latest" ]]; then
            POST_FLAGS+=" -DPNG_LIBRARY=${GITHUB_WORKSPACE}/ddnet-libs/png/mac/libfat/libpng16.16.dylib"
            POST_FLAGS+=" -DPNG_INCLUDEDIR=${GITHUB_WORKSPACE}/ddnet-libs/png/include"
            POST_FLAGS+=" -DSDL2_LIBRARY=${GITHUB_WORKSPACE}/ddnet-libs/sdl/mac/libfat/SDL2.framework/Versions/A/SDL2"
            POST_FLAGS+=" -DSDL2_INCLUDEDIR=${GITHUB_WORKSPACE}/ddnet-libs/sdl/mac/libfat/SDL2.framework/Headers"
        fi
        mkdir release
        cd release
        ${{ matrix.cmake-path }}cmake -E env ${{ matrix.cmake-init-env }} $ENVFLAGS ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} $POST_FLAGS -DCMAKE_BUILD_TYPE=Release -DDOWNLOAD_GTEST=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. ..
        ${{ matrix.cmake-path }}cmake --build . --config Release --target everything ${{ matrix.build-args }}

    - name: Package
      run: |
        cd release
        ${{ matrix.cmake-path }}cmake --build . --config Release --target package_default ${{ matrix.build-args }}
        mkdir artifacts
        mv ${{ matrix.package-file }} artifacts

    - name: Upload Artifacts
      continue-on-error: ${{ contains(matrix.os, 'macOS') }}
      uses: actions/upload-artifact@v4
      with:
        name: ddnet-${{ matrix.os }}
        path: release/artifacts

  build-android:
    runs-on: ubuntu-24.04
    env:
      CARGO_HTTP_MULTIPLEXING: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Prepare Linux
      run: |
        sudo apt-get update -y
        sudo apt-get install ninja-build openjdk-21-jdk openssl
        curl -LO https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-Linux-x86_64.tar.gz
        mkdir -p /home/runner/cmake
        tar --strip-components 1 -C /home/runner/cmake -xf cmake-3.22.1-Linux-x86_64.tar.gz
        rustup default 1.92.0
        cargo install cargo-ndk
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add aarch64-linux-android
        rustup target add x86_64-linux-android
        scripts/android/download_android_sdk.sh /home/runner

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.3.296.0
        cache: true

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
          workspaces: |
              src/mastersrv
              src/masterping
              ./

    - name: Build Android app
      env:
        TW_KEY_NAME: /home/runner/DDNet.jks
        TW_KEY_ALIAS: DDNet-Key
        VERSION: ${{ secrets.VERSION }}
      run: |
        printf '%s' "$VERSION" | base64 -d > "$GITHUB_WORKSPACE/versioninfo.h"
        export TW_KEY_PW="$(openssl rand -base64 32)"
        keytool -genkey -v -keystore "$TW_KEY_NAME" -keyalg RSA -keysize 2048 -validity 10000 -alias "$TW_KEY_ALIAS" -storepass "$TW_KEY_PW" -dname "CN=DDNet CI, OU=DDNet, O=DDNet"
        export ANDROID_HOME="/home/runner/Android/Sdk"
        unset ANDROID_SDK_ROOT
        export PATH=/home/runner/cmake/bin:$PATH
        scripts/android/cmake_android.sh all DDNet org.ddnet.client Release build-android
        mkdir artifacts
        mv build-android/DDNet.apk artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ddnet-android
        path: artifacts
